name: MCC Halo Editing Kit Feedback Form
description: Submit feedback for the MCC Halo Editing Kits.
body:
- type: markdown
  attributes:
    value: "## MCC Halo Editing Kit Feedback Form"
- type: dropdown
  id: toolkit
  attributes:
    label: "Which game's editing kit does your feedback pertain to?"
    description: If your feedback is for more than one game, submit another form.
    options:
      - H1EK
      - H2EK
      - H3EK
      - H3ODSTEK
  validations:
    required: true
- type: checkboxes
  id: tool-types
  attributes:
    label: Which tools are affected by the issue?
    description: Check each tool that the issue is affecting. If the issue is specific to MCC, include that.
    options:
      - label: Guerilla
      - label: Sapien
      - label: Tag Test
      - label: Tool
      - label: Tool_Fast
      - label: MCC
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Feedback
    description: Write down your feedback here.
  validations:
    required: true
- type: textarea
  id: media
  attributes:
    label: Media
    description: If your feedback has a visual portion, include media here.
  validations:
    required: false
