name: MCC Halo Editing Kit Issue Form
description: Create a new issue for the the MCC Halo Editing Kit.
labels: ["triage", "confirmation needed"]
body:
- type: markdown
  attributes:
    value: "## MCC Halo Editing Kit Issue Form"
- type: dropdown
  id: type
  attributes:
    label: "Issue type: Is this a bug or feature request?"
    description: If you are unsure just make a best effort.
    options:
      - Bug
      - Feature request
      - Other
  validations:
    required: true
- type: dropdown
  id: toolkit
  attributes:
    label: "Which game's editing kit is affected by the issue?"
    description: If the issue affects more than one game, submit another form.
    options:
      - H1EK
      - H2EK
      - H3EK
      - H3ODSTEK
      - HREK
      - H4EK
      - H2AEK
  validations:
    required: true
- type: checkboxes
  id: tool-types
  attributes:
    label: Which tools are affected by the issue?
    description: Check each tool that the issue is affecting. Only report in-game issues that are modding related. Please report all other in-game issue through [the official channels](https://support.halowaypoint.com/hc/en-us/articles/360036218972-How-to-Submit-a-Halo-Support-Ticket)
    options:
      - label: Guerilla (`guerilla.exe`)
      - label: Sapien (`sapien.exe`)
      - label: Standalone (`halox_tag_test.exe`)
      - label: Tool (`tool.exe`)
      - label: Tool Fast (`tool_fast.exe` - unsupported)
      - label: MegaloEdit (`MegaloEdit.exe`)
      - label: In-game (MCC)
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Issue description
    description: Describe the issue in detail. If this is a visual issue include screenshots or videos.
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction steps
    description: Write steps on how to reproduce the issue. Please include as much detail as you can. Upload any custom tags required to reproduce the issue. Please do not upload compiled map files. For some feedback issues this might not be applicable - just enter "N/A" so Github will let you submit the issue.
  validations:
    required: true
- type: textarea
  id: debug_logs
  attributes:
    label: Debug logs
    description: Please upload `crash_info.txt` and `debug.txt` here if possible. **Note these files can include your computer and username so if that's a concern you can edit them to redact that information.**
  validations:
    required: false
- type: dropdown
  id: repro-success
  attributes:
    label: How often does the issue occur?
    description: When attempting to reproduce the issue, how often are you successful?
    options:
      - Once
      - 25%
      - 50%
      - 75%
      - 100%
  validations:
    required: true
- type: textarea
  id: impact
  attributes:
    label: Issue impact
    description: How impactful is the issue? Does this bug/lack of feature break your workflow? Are there any workarounds for it?
  validations:
    required: false
- type: textarea
  id: comments
  attributes:
    label: Additional comments
    description: Write any additional comments you have here.
  validations:
    required: false

